### ISSUE TITLE
json.decoder.JSONDecodeError:

### ISSUE THREAD

**Issue by dnkls** [jcamiloangarita/stocker#29]
I keep getting this error every time ☹️

```
`2021-10-26 02:10:24.399589: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-10-26 02:10:24.399916: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[*********************100%***********************]  1 of 1 completed
Traceback (most recent call last):
  File "C:\Users\xans0\Desktop\TgTwitterStreamer\Stock\stock.py", line 9, in <module>
    correlation(stocks, interest=True, wiki_views=True, indicators=True)
  File "C:\Users\xans0\Desktop\TgTwitterStreamer\venv\lib\site-packages\stocker\get_data.py", line 135, in correlation
    df = total(stock, years, interest, wiki_views, indicators, period)
  File "C:\Users\xans0\Desktop\TgTwitterStreamer\venv\lib\site-packages\stocker\get_data.py", line 114, in total
    company = company_name(stock)  # get the name of the company
  File "C:\Users\xans0\Desktop\TgTwitterStreamer\venv\lib\site-packages\stocker\get_data.py", line 18, in company_name
    company = requests.get(url).json()['ResultSet']['Result'][0]['name']   # saving the name as 'company'
  File "C:\Users\xans0\Desktop\TgTwitterStreamer\venv\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\xans0\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\xans0\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\xans0\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Process finished with exit code 1
`
```

**Comment by jcamiloangarita** [comment]
There was an issue related to the function for translating the stock symbol to a proper company name for checking the general interest. A fix was already pushed and there's a new version (v0.1.11).

The issue should be solved now, feel free to test it and open a new ticket if something else arise.
